// All Figma commands supported by the MCP server and plugin

export type FigmaCommand =
  // Document & Selection
  | "get_document_info"
  | "get_file_info"
  | "get_selection"
  | "read_my_design"
  | "get_node_info"
  | "get_node_tree"
  | "get_nodes_info"
  | "scan_nodes_by_types"
  | "get_css"
  | "find_nodes"
  | "get_bound_variables"
  // Creation
  | "create_rectangle"
  | "create_frame"
  | "create_text"
  | "create_ellipse"
  | "create_polygon"
  | "create_star"
  | "create_line"
  | "create_component_instance"
  | "create_section"
  | "create_node_from_svg"
  | "create_connector"
  | "create_table"
  | "create_sticky"
  | "create_code_block"
  | "create_slice"
  // Modification
  | "move_node"
  | "resize_node"
  | "clone_node"
  | "delete_node"
  | "delete_multiple_nodes"
  | "rename_node"
  | "set_opacity"
  | "reorder_node"
  | "set_visible"
  | "set_locked"
  | "reparent_node"
  | "set_rotation"
  | "set_relaunch_data"
  | "get_relaunch_data"
  // Styling
  | "set_fill_color"
  | "set_stroke_color"
  | "set_corner_radius"
  | "set_blend_mode"
  | "set_gradient_fill"
  | "set_clips_content"
  | "set_layout_grids"
  | "set_aspect_ratio"
  // Effects
  | "add_drop_shadow"
  | "add_inner_shadow"
  | "add_blur"
  | "add_background_blur"
  | "remove_effects"
  // Text
  | "scan_text_nodes"
  | "set_text_content"
  | "set_multiple_text_contents"
  | "set_text_style_range"
  // Layout
  | "set_layout_mode"
  | "set_padding"
  | "set_axis_align"
  | "set_layout_sizing"
  | "set_item_spacing"
  // Design system
  | "get_design_system"
  | "scan_token_drift"
  // Components
  | "get_local_components"
  | "get_instance_overrides"
  | "set_instance_overrides"
  | "create_component"
  | "create_component_set"
  | "get_component_properties"
  | "set_component_properties"
  | "detach_instance"
  // Variables
  | "get_variable_collections"
  | "get_variables"
  | "create_variable_collection"
  | "create_variable"
  | "update_variable"
  | "delete_variable"
  | "delete_variable_collection"
  | "update_variable_collection"
  | "add_mode"
  | "remove_mode"
  | "rename_mode"
  | "set_variable_scopes"
  | "set_variable_code_syntax"
  | "remove_variable_code_syntax"
  | "create_variable_alias"
  | "bind_variable"
  | "unbind_variable"
  | "set_node_variable_mode"
  | "get_resolved_variable_modes"
  // Styles
  | "get_styles"
  | "create_paint_style"
  | "create_text_style"
  | "create_effect_style"
  | "create_grid_style"
  | "update_style"
  | "delete_style"
  | "apply_style"
  | "reorder_style"
  // Export
  | "export_node_as_image"
  | "get_screenshot"
  | "create_image_from_url"
  // Page
  | "get_pages"
  | "create_page"
  | "rename_page"
  | "delete_page"
  | "switch_page"
  | "set_page_background"
  | "get_flow_starting_points"
  // Structure
  | "group_nodes"
  | "ungroup_nodes"
  | "flatten_node"
  | "boolean_operation"
  | "create_component_from_node"
  // Library
  | "import_component_by_key"
  | "import_style_by_key"
  | "import_variable_by_key"
  // Document extras
  | "get_selection_colors"
  | "set_file_thumbnail"
  | "figma_notify"
  // Constraints
  | "set_constraints"
  | "set_min_max_size"
  // Annotations
  | "get_annotations"
  | "set_annotation"
  | "set_multiple_annotations"
  // Prototype
  | "get_reactions"
  | "set_default_connector"
  | "create_connections"
  // Viewport
  | "set_focus"
  | "set_selections"
  | "get_viewport"
  | "set_viewport"
  // Plugin data
  | "set_plugin_data"
  | "get_plugin_data"
  // Image fill
  | "set_image_fill"
  // Batch
  | "batch_execute"
  | "execute_code"
  // Room
  | "join";

// Color type used across the system (0-1 range)
export interface RGBAColor {
  r: number;
  g: number;
  b: number;
  a?: number;
}

// Gradient stop for gradient fills
export interface GradientStop {
  position: number;
  color: RGBAColor;
}
